name: diet_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  get: ^3.26.0
  page_view_indicators: ^2.0.0
  titled_navigation_bar: ^4.1.0
  vexana: ^1.4.1
  flutter_slidable: ^0.5.7
  date_picker_timeline: ^1.2.3
  sleek_circular_slider: ^1.2.0+web
  google_fonts: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.4+1
  effective_dart: ^1.3.1
  pedantic: ^1.11.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/onboard/
    - assets/images/login/
    - assets/images/sign_up/
    - assets/images/exercises/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf

flutter_native_splash:
  image: assets/images/logo.png
  color: "#ffffff"